### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [itzmeanjan/mapZ#1]
Hi there @itzmeanjan  I'm a graphic artist and would like to contribute by designing a logo here. If you are interested I will be gladly begin my design. Regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , it'd be great to have logo for this mapping application. Happy Designing :+1:

**Comment by Tobaloidee** [comment]
Hi @itzmeanjan thank you for the response! Will design and show it here after

**Comment by Tobaloidee** [comment]
Here's what I came up with @itzmeanjan  I hope you like it! Still open for your suggestions/opinions

![mapZ-01-01](https://user-images.githubusercontent.com/36028424/56153398-a06c1500-5fe8-11e9-9182-366f9b8bc4d4.png)

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee nice work :heart:

Great design idea, which displays insight of application. I'll put a link, pointing to your profile and work, in this repo.

Keep it up :+1:

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee, I've put a link back to your work in [README.md](https://github.com/itzmeanjan/mapZ/blob/master/README.md).

**Comment by Tobaloidee** [comment]
Sir @itzmeanjan here's the PR #2 for a better display of your new logo and I uploaded it into the logo folder. 

Thanks so much! Best Regards! 😊👍

**Comment by Tobaloidee** [comment]
Hi @itzmeanjan you can get the other versions and file formats of your logo [HERE](https://drive.google.com/drive/u/0/folders/1XT-8KPzADmfmfqUDqHTj-9lX4q5Fk_rW) 

Thanks again! and Best regards!

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee, that's great :+1:

**Comment by Tobaloidee** [comment]
Hi @itzmeanjan! I have seen just now your other projects/repositories...I thought of doing a logo for them too. Are you interested? I am.. 😊

**Comment by itzmeanjan** [comment]
Hei @Tobaloidee , I was thinking about asking you for making logo for other projects like **transferZ**, which I released a few days ago. Please make so, I'll be happy to give you credit. After you're done submit a PR :wink:.

**Comment by Tobaloidee** [comment]
That's great news! I will definitely work for your other projects..you can count on me with those logos 👍

**Comment by Tobaloidee** [comment]
Will just open an issue with those projects whenever I am done with the designs
